{% set name = "brokenaxes" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brokenaxes-{{ version }}.tar.gz
  sha256: bfa68242f003c02fe57ce7b5c5671c78c733ac8cc51a2be0f3ee6906c18e5d49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - matplotlib-base
    - python >=3.5

test:
  imports:
    - brokenaxes

about:
  home: https://github.com/bendichter/brokenaxes
  summary: Create broken axes
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - dpryan79
